<a href="https://colab.research.google.com/github/Mugeshkumar133/Product_Supply_data_sql/blob/main/Panda_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
purchase_df=pd.read_csv("/content/Assignment-1_Data (1).csv",sep=";")
purchase_df

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,01.12.2010 08:26,"2,55",17850.0,United Kingdom
1,536365,WHITE METAL LANTERN,6,01.12.2010 08:26,"3,39",17850.0,United Kingdom
2,536365,CREAM CUPID HEARTS COAT HANGER,8,01.12.2010 08:26,"2,75",17850.0,United Kingdom
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,01.12.2010 08:26,"3,39",17850.0,United Kingdom
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,01.12.2010 08:26,"3,39",17850.0,United Kingdom
...,...,...,...,...,...,...,...
213453,556241,RED POLKADOT BEAKER,48,09.06.2011 16:04,"0,39",12597.0,Spain
213454,556241,BLUE EGG SPOON,24,09.06.2011 16:04,"0,12",12597.0,Spain
213455,556241,RED EGG SPOON,24,09.06.2011 16:04,"0,12",12597.0,Spain
213456,556241,ENAMEL PINK COFFEE CONTAINER,12,09.06.2011 16:04,"0,83",12597.0,Spain
213457,556241,POLKADOT COFFEE CUP & SAUCER PINK,24,09.06.2011 1,NaN,NaN,NaN

In [4]:
purchase_df.info() #For initial checking

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213458 entries, 0 to 213457
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   BillNo      213458 non-null  int64
 1   Itemname    212604 non-null  object
 2   Quantity    213458 non-null  int64
 3   Date        213458 non-null  object
 4   Price       213457 non-null  object
 5   CustomerID  150785 non-null  float64
 6   Country     213457 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 11.4+ MB

In [70]:
purchase_df.dropna(subset=["Itemname"])
purchase_df.dropna(subset=["Country"])
purchase_df.dropna(subset=["CustomerID"])

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country,Total Price
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,01.12.2010 08:26,2.55,17850.0,United Kingdom,15.30
1,536365,WHITE METAL LANTERN,6,01.12.2010 08:26,3.39,17850.0,United Kingdom,20.34
2,536365,CREAM CUPID HEARTS COAT HANGER,8,01.12.2010 08:26,2.75,17850.0,United Kingdom,22.00
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,01.12.2010 08:26,3.39,17850.0,United Kingdom,20.34
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,01.12.2010 08:26,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...
213452,556241,BLUE POLKADOT BEAKER,48,09.06.2011 16:04,0.39,12597.0,Spain,18.72
213453,556241,RED POLKADOT BEAKER,48,09.06.2011 16:04,0.39,12597.0,Spain,18.72
213454,556241,BLUE EGG SPOON,24,09.06.2011 16:04,0.12,12597.0,Spain,2.88
213455,556241,RED EGG SPOON,24,09.06.2011 16:04,0.12,12597.0,Spain,2.88
213456,556241,ENAMEL PINK COFFEE CONTAINER,12,09.06.2011 16:04,0.83,12597.0,Spain,9.96

In [71]:
purchase_df.columns

Index(['BillNo', 'Itemname', 'Quantity', 'Date', 'Price', 'CustomerID',
       'Country', 'Total Price'],
      dtype='object')

In [72]:
# Let we convert the price in str format to float type for calculation purposes as we have the quantity in float type

In [73]:
def convert(x):
  a=str(x)
  b=a.replace(",",".")
  c=float(b)
  return c
purchase_df["Price"]= purchase_df["Price"].apply(lambda x: convert(x))

In [74]:
purchase_df["Price"]

0         2.55
1         3.39
2         2.75
3         3.39
4         3.39
          ...
213453    0.39
213454    0.12
213455    0.12
213456    0.83
213457     NaN
Name: Price, Length: 213458, dtype: float64

In [75]:
purchase_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213458 entries, 0 to 213457
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   BillNo       213458 non-null  int64
 1   Itemname     212604 non-null  object
 2   Quantity     213458 non-null  int64
 3   Date         213458 non-null  object
 4   Price        213457 non-null  float64
 5   CustomerID   150785 non-null  float64
 6   Country      213457 non-null  object
 7   Total Price  213457 non-null  float64
dtypes: float64(3), int64(2), object(3)
memory usage: 13.0+ MB

In [76]:
# Q1: Which product was frequently bought?

In [79]:
frequently_sold_items=purchase_df.loc[purchase_df.groupby("Itemname")["Quantity"].transform(sum).idxmax()]
frequently_sold_items

BillNo                                 541431
Itemname       MEDIUM CERAMIC TOP STORAGE JAR
Quantity                                74215
Date                         18.01.2011 10:01
Price                                    1.04
CustomerID                            12346.0
Country                        United Kingdom
Total Price                           77183.6
Name: 59999, dtype: object

In [45]:
#Answer1: Frequently sold items is   "MEDIUM CERAMIC TOP STORAGE JAR"      | Total Quantity sold is 74215.0

In [80]:
purchase_df.dropna(subset=["Quantity"],inplace=True)
purchase_df.dropna(subset=["Price"],inplace=True)

In [47]:
purchase_df["Total Price"]=purchase_df["Price"]*purchase_df["Quantity"]
purchase_df["Total Price"]

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...
213453    18.72
213454     2.88
213455     2.88
213456     9.96
213457      NaN
Name: Total Price, Length: 213458, dtype: float64

In [ ]:
# How much on an average does the customer spent ?

In [58]:
average_spent=purchase_df.groupby("CustomerID")["Total Price"].mean().reset_index()[["CustomerID","Total Price"]]
average_spent.sort_values(by="Total Price",ascending =False)

      CustomerID   Total Price
0        12346.0  77183.600000
1594     15749.0   4453.430000
2681     18087.0   3202.920000
370      13135.0   3096.000000
1956     16532.0   1910.400000
...          ...           ...
622      13684.0      2.241000
1475     15483.0      2.126852
1483     15503.0      2.101286
2553     17816.0      1.937273
1918     16446.0      1.450000

[2772 rows x 2 columns]

In [ ]:
#Recently which products are prefered by the customers?

In [60]:
purchase_df["Date"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 213458 entries, 0 to 213457
Series name: Date
Non-Null Count   Dtype
--------------   -----
213458 non-null  object
dtypes: object(1)
memory usage: 1.6+ MB

In [83]:
purchase_df["Date"]=pd.to_datetime(purchase_df["Date"],format="%d.%m.%Y %H:%M")

In [84]:
purchase_df["Date"]

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
213452   2011-06-09 16:04:00
213453   2011-06-09 16:04:00
213454   2011-06-09 16:04:00
213455   2011-06-09 16:04:00
213456   2011-06-09 16:04:00
Name: Date, Length: 213457, dtype: datetime64[ns]

In [86]:
purchase_df["Purchase_date"]=pd.to_datetime(purchase_df["Date"]).dt.date
purchase_df["Purchase_date"]

0         2010-12-01
1         2010-12-01
2         2010-12-01
3         2010-12-01
4         2010-12-01
             ...
213452    2011-06-09
213453    2011-06-09
213454    2011-06-09
213455    2011-06-09
213456    2011-06-09
Name: Purchase_date, Length: 213457, dtype: object

In [88]:
purchase_df["Time"]=pd.to_datetime(purchase_df["Date"]).dt.time
purchase_df["Time"]

0         08:26:00
1         08:26:00
2         08:26:00
3         08:26:00
4         08:26:00
            ...
213452    16:04:00
213453    16:04:00
213454    16:04:00
213455    16:04:00
213456    16:04:00
Name: Time, Length: 213457, dtype: object

In [99]:
recent_purchase=purchase_df.sort_values(("Purchase_date"),ascending=False).head(100)

In [100]:
recent_purchase

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country,Total Price,Purchase_date,Time
213456,556241,ENAMEL PINK COFFEE CONTAINER,12,2011-06-09 16:04:00,0.83,12597.0,Spain,9.96,2011-06-09,16:04:00
212727,556189,RED DINER WALL CLOCK,2,2011-06-09 11:57:00,8.50,15615.0,United Kingdom,17.00,2011-06-09,11:57:00
212721,556189,LUNCH BAG APPLE DESIGN,10,2011-06-09 11:57:00,1.65,15615.0,United Kingdom,16.50,2011-06-09,11:57:00
212722,556189,JUMBO BAG APPLES,20,2011-06-09 11:57:00,2.08,15615.0,United Kingdom,41.60,2011-06-09,11:57:00
212723,556189,HANGING HEART ZINC T-LIGHT HOLDER,12,2011-06-09 11:57:00,0.85,15615.0,United Kingdom,10.20,2011-06-09,11:57:00
...,...,...,...,...,...,...,...,...,...,...
212641,556183,JUMBO BAG SPACEBOY DESIGN,10,2011-06-09 11:37:00,2.08,13134.0,United Kingdom,20.80,2011-06-09,11:37:00
212640,556183,JUMBO BAG DOLLY GIRL DESIGN,10,2011-06-09 11:37:00,2.08,13134.0,United Kingdom,20.80,2011-06-09,11:37:00
212639,556183,CANDLEHOLDER PINK HANGING HEART,6,2011-06-09 11:37:00,2.95,13134.0,United Kingdom,17.70,2011-06-09,11:37:00
212638,556183,METAL SIGN TAKE IT OR LEAVE IT,6,2011-06-09 11:37:00,2.95,13134.0,United Kingdom,17.70,2011-06-09,11:37:00
212637,556183,DANISH ROSE DECORATIVE PLATE,12,2011-06-09 11:37:00,2.10,13134.0,United Kingdom,25.20,2011-06-09,11:37:00

In [101]:
recent_purchase.dropna(subset="Country")

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country,Total Price,Purchase_date,Time
213456,556241,ENAMEL PINK COFFEE CONTAINER,12,2011-06-09 16:04:00,0.83,12597.0,Spain,9.96,2011-06-09,16:04:00
212727,556189,RED DINER WALL CLOCK,2,2011-06-09 11:57:00,8.50,15615.0,United Kingdom,17.00,2011-06-09,11:57:00
212721,556189,LUNCH BAG APPLE DESIGN,10,2011-06-09 11:57:00,1.65,15615.0,United Kingdom,16.50,2011-06-09,11:57:00
212722,556189,JUMBO BAG APPLES,20,2011-06-09 11:57:00,2.08,15615.0,United Kingdom,41.60,2011-06-09,11:57:00
212723,556189,HANGING HEART ZINC T-LIGHT HOLDER,12,2011-06-09 11:57:00,0.85,15615.0,United Kingdom,10.20,2011-06-09,11:57:00
...,...,...,...,...,...,...,...,...,...,...
212641,556183,JUMBO BAG SPACEBOY DESIGN,10,2011-06-09 11:37:00,2.08,13134.0,United Kingdom,20.80,2011-06-09,11:37:00
212640,556183,JUMBO BAG DOLLY GIRL DESIGN,10,2011-06-09 11:37:00,2.08,13134.0,United Kingdom,20.80,2011-06-09,11:37:00
212639,556183,CANDLEHOLDER PINK HANGING HEART,6,2011-06-09 11:37:00,2.95,13134.0,United Kingdom,17.70,2011-06-09,11:37:00
212638,556183,METAL SIGN TAKE IT OR LEAVE IT,6,2011-06-09 11:37:00,2.95,13134.0,United Kingdom,17.70,2011-06-09,11:37:00
212637,556183,DANISH ROSE DECORATIVE PLATE,12,2011-06-09 11:37:00,2.10,13134.0,United Kingdom,25.20,2011-06-09,11:37:00

In [102]:
recent_purchase.isnull().sum()

BillNo            0
Itemname          0
Quantity          0
Date              0
Price             0
CustomerID       14
Country           0
Total Price       0
Purchase_date     0
Time              0
dtype: int64

In [105]:
recent_purchase=recent_purchase.dropna()

In [107]:
recent_purchase.isnull().sum()

BillNo           0
Itemname         0
Quantity         0
Date             0
Price            0
CustomerID       0
Country          0
Total Price      0
Purchase_date    0
Time             0
dtype: int64

In [108]:
recent_purchase.columns

Index(['BillNo', 'Itemname', 'Quantity', 'Date', 'Price', 'CustomerID',
       'Country', 'Total Price', 'Purchase_date', 'Time'],
      dtype='object')

In [128]:
# list of items bought by the customers recently with their total quantity summed up

In [136]:
recent_purchase.groupby("Itemname")["Quantity"].sum()

Itemname
12 COLOURED PARTY BALLOONS          20
3 STRIPEY MICE FELTCRAFT             6
ASSORTED COLOUR BIRD ORNAMENT       16
ASSORTED COLOURS SILK FAN           48
BALLOONS  WRITING SET               12
                                    ..
WRAP GREEN PEARS                    25
WRAP PINK FAIRY CAKES               25
WRAP RED APPLES                     25
ZINC HEART FLOWER T-LIGHT HOLDER     8
ZINC HEARTS PLANT POT HOLDER         8
Name: Quantity, Length: 84, dtype: int64

In [140]:
recently_purchased_topmost_item=recent_purchase.groupby("Itemname")["Quantity"].sum().idxmax()
recently_purchased_topmost_item

'ASSORTED COLOURS SILK FAN'

In [141]:
#Recently purchased item by all customers which is much prefered is "ASSORTED COLOURS SILK FAN"